version: "3"

services:

  postgres:
    image: postgres
    container_name: postgres
    volumes:
      - progresDB:/var/lib/postgresql/data
    env_file:
      - ./.env
    ports:
      - "5432:5432"

  # pgAdmin:
  #   image: dpage/pgadmin4
  #   container_name: pgAdmin
  #   env_file:
  #     - ./.env
  #   ports:
  #     - "5050:80"

volumes:
  progresDB:
