[package]
name = "project_minigrep"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

# REF: https://www.youtube.com/watch?v=4TI153PIEDQ
[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3
